In [4]:
import numpy as np
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard
import os

In [7]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [8]:
X_train.shape

(404, 13)

In [9]:
X_valid.shape

(102, 13)

In [10]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [11]:
y_train[0]

np.float64(15.2)

In [12]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

C:\Users\veera\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 32)                  │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 16)                  │              64 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,185 (4.63 KB)

 Trainable params: 1,089 (4.25 KB)

 Non-trainable params: 96 (384.00 B)

In [15]:
model.compile(loss='mean_squared_error', optimizer='adam', )

In [16]:
output_dir = 'model_output/'

In [18]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [19]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [25]:
from tensorflow.keras.callbacks import ModelCheckpoint

#Define the Nodel.Checkpoint callback
output_path = "model_output/regression_baseline"
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.weights.h5',
                                save_weights_only=True)

#Your model training code goes here

In [26]:
tensorboard = TensorBoard(log_dir='logs/' + run_name)

In [27]:
model.fit(X_train, y_train,
          batch_size=8, epochs=32, verbose=1,
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint, tensorboard]) 

Epoch 1/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 527.2442 - val_loss: 534.7018
Epoch 2/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 522.1666 - val_loss: 561.7728
Epoch 3/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 529.6004 - val_loss: 571.9896
Epoch 4/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 460.8722 - val_loss: 523.3240
Epoch 5/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 438.1018 - val_loss: 511.2947
Epoch 6/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 444.0251 - val_loss: 491.8591
Epoch 7/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 372.4821 - val_loss: 513.9309
Epoch 8/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 365.8254 - val_loss: 506.0706
Epoch 9/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 316.5351 - val_loss: 495.5800
Epoch 10/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 252.2108 - val_loss: 413.0950
Epoch 11/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 220.7440 - val_loss: 330.5639
Epoch 12/32
51/51 ━━━━━━━━━━━

In [28]:
import os

#List files in the directory
output_path = "model_output/regression_baseline"
files = os.listdir(output_path)
print(files)

['weights.01.weights.h5', 'weights.02.weights.h5', 'weights.03.weights.h5', 'weights.04.weights.h5', 'weights.05.weights.h5', 'weights.06.weights.h5', 'weights.07.weights.h5', 'weights.08.weights.h5', 'weights.09.weights.h5', 'weights.10.weights.h5', 'weights.11.weights.h5', 'weights.12.weights.h5', 'weights.13.weights.h5', 'weights.14.weights.h5', 'weights.15.weights.h5', 'weights.16.weights.h5', 'weights.17.weights.h5', 'weights.18.weights.h5', 'weights.19.weights.h5', 'weights.20.weights.h5', 'weights.21.weights.h5', 'weights.22.weights.h5', 'weights.23.weights.h5', 'weights.24.weights.h5', 'weights.25.weights.h5', 'weights.26.weights.h5', 'weights.27.weights.h5', 'weights.28.weights.h5', 'weights.29.weights.h5', 'weights.30.weights.h5', 'weights.31.weights.h5', 'weights.32.weights.h5']


In [29]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [30]:
y_valid[42]

np.float64(14.1)

In [33]:
model.predict(np.reshape(X_valid[42], [1, 13]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step


array([[24.959194]], dtype=float32)

In [38]:
from sklearn.metrics import accuracy_score

#Assume y true and y pred are the true Labels and predicted Labels respectively
y_true = [0, 1, 0, 1, 1]
y_pred = [0, 1, 0, 0, 1]

#Calculate accuracy
accuracy = accuracy_score(y_true, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 80.00%
